### ISSUE TITLE
html 404 - url change again?

### ISSUE THREAD

**Issue by PoorNewb23** [conoro/yunmai-data-extract#11]
Hi,
this great app doesn't seem to work anymore.

Even after changing url to chart-list,

the best I get is:
{ result: { msgcn: '成功!', code: 0, msg: 'Ok!' },
  data: { total: 0, rows: [] } }
LevelDB updated
CSV updated

**Comment by conoro** [comment]
Yes I'm afraid I have the same problem. I have not been able to find a fix but I'll continue to try.

**Comment by PoorNewb23** [comment]
It's much appreciated. Now that yunmai devices are supported by openScale, all that remains is to grab the historical dat aonce and we can forget about them for good.

**Comment by k-meeks** [comment]
Mine continued to work until early this summer, I just now got around to looking at why  it stopped. The URL in index.js is almost right,  but they got a bit clever it seems and put a %26 in front of starttime, and it has to be %26

I updated my version with this and it works fine again.
uri: 'http://intdata.iyunmai.com/api/android/scale/list.json?code='+code+'&%26startTime='+epochtime+'&lang='+lang+'&userId='+userId+'&versionCode=2&token='+token,

**Comment by conoro** [comment]
Oh fantastic @k-meeks . It's working for me now again after a long break. And all my data from the past year was accessible so I could download it all. Thanks!

**Comment by PoorNewb23** [comment]
Wortked for me as well.

Bye bye Yunmai!
