### ISSUE TITLE
2018-08 URL update

### ISSUE THREAD

**Issue by xurizaemon** [conoro/yunmai-data-extract#4]
Looks like the URL has been updated once more! Now data is at `intdata.iyunmai.com` (at least for my scales/Android app), and introduces a new versionCode parameter which seems to me to be required. Scale URL component is no longer present.

I have a Yunmai M1501 and Yunmai app v2.4.2.

**Comment by conoro** [comment]
Thanks. scale param definitely doesn't work on new URL so I've removed completely.
