### ISSUE TITLE
Unable to capture any data

### ISSUE THREAD

**Issue by Aethalides** [conoro/yunmai-data-extract#43]
Whilst following the instructions, the captured packets are now all SSL. So unable to be decoded.

It seems that Yuma's remote server has changed to HTTPS now.

I do not think there's a solution for this, except if we have a copy of the private key of their certificate (unlikely)....

**Comment by conoro** [comment]
Thanks Andy. I'll update the readme to tell people not to bother with the code. A pity Yunmai won't open up the API like Withings. I switched to Wthings because of this.

**Comment by arthurfsy2** [comment]
I have achieved this through reverse engineering[arthurfsy2/yunmai_weight_extract2json](https://github.com/arthurfsy2/yunmai_weight_extract2json): I log in with my account and password to get cookies and all the weight data. But I am not sure whether the overseas version of Yunmai Haoqing Body Fat Scale APP can get data through this method.
